#!/bin/bash

ln -sf $HOME/Repos/github.com/mattiwos/dotfiles/bashconfig $HOME/.bash_aliases
ls -l $HOME/.bash_aliases
#linux
#ln -sf $PWD/vimrc $HOME/.vimrc
#ls -l $HOME/.vimrc
ln -sf $HOME/Repos/github.com/mattiwos/dotfiles/vimrc $HOME/.vimrc
ls -l $HOME/.vimrc
ln -sf $HOME/Repos/github.com/mattiwos/dotfiles/tmux.conf $HOME/.tmux.conf
#ls -l $HOME/.tmux.conf

